shell script improvements

diff --git a/.local/scripts/generic/chafa-cache b/.local/scripts/generic/chafa-cache
--- a/.local/scripts/generic/chafa-cache
+++ b/.local/scripts/generic/chafa-cache
@@ -8,19 +8,19 @@
 
 declare CHAFA_IMG_CACHE URL HASH TARGET_FILE
 
-CHAFA_IMG_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/chafa_url_cache"
-mkdir -p "$CHAFA_IMG_CACHE"
+CHAFA_IMG_CACHE="${XDG_CACHE_HOME:-${HOME}/.cache}/chafa_url_cache"
+mkdir -p "${CHAFA_IMG_CACHE}"
 
 URL="${1:?Must pass URL display as first argument\!}"
 shift # remove URL from argument list
-HASH="$(sha1sum <<<"$URL" | cut -d" " -f1)"
+HASH="$(sha1sum <<<"${URL}" | cut -d" " -f1)"
 TARGET_FILE="${CHAFA_IMG_CACHE}/${HASH}.${URL##*.}"
 
-if [[ ! -e "$TARGET_FILE" ]]; then
-	wget -q "$URL" -O "$TARGET_FILE" || {
-		printf "Failed to download '%s'\n" "$URL"
+if [[ ! -e "${TARGET_FILE}" ]]; then
+	wget -q "${URL}" -O "${TARGET_FILE}" || {
+		printf "Failed to download '%s'\n" "${URL}"
 		exit 1
 	}
 fi
 
-exec chafa "$@" "$TARGET_FILE"
+exec chafa "$@" "${TARGET_FILE}"
diff --git a/.local/scripts/generic/gitopen b/.local/scripts/generic/gitopen
--- a/.local/scripts/generic/gitopen
+++ b/.local/scripts/generic/gitopen
@@ -3,8 +3,8 @@
 # it in your browser
 
 if GIT_URL=$(giturl); then
-	openurl "$GIT_URL"
+	openurl "${GIT_URL}"
 else
-	echo "$GIT_URL" >&2 # print error
+	echo "${GIT_URL}" >&2 # print error
 	exit 1
 fi
diff --git a/.local/scripts/generic/youtube-thumbnail b/.local/scripts/generic/youtube-thumbnail
--- a/.local/scripts/generic/youtube-thumbnail
+++ b/.local/scripts/generic/youtube-thumbnail
@@ -1,9 +1,9 @@
 #!/bin/sh
 # preview a youtube thumbnail fullscreen
 YOUTUBE_URL="${1:?Provide Youtube URL as the first argument}"
-IMAGE_URL="$(curl -s "$YOUTUBE_URL" | pup 'link[itemprop="thumbnailUrl"] attr{href}' | head -n 1)" || {
-	echo "Couldn't download "
+IMAGE_URL="$(curl -s "${YOUTUBE_URL}" | pup 'link[itemprop="thumbnailUrl"] attr{href}' | head -n 1)" || {
+	printf "Couldn't download %s\n" "${YOUTUBE_URL}"
 	exit 1
 }
 # https://sean.fish/d/previewurlpic?dark
-previewurlpic "$IMAGE_URL"
+previewurlpic "${IMAGE_URL}"
