redirect errors to stderr

diff --git a/.local/scripts/generic/githubopen b/.local/scripts/generic/githubopen
--- a/.local/scripts/generic/githubopen
+++ b/.local/scripts/generic/githubopen
@@ -9,5 +9,5 @@
 if GIT_URL=$(giturl); then
 	openurl "${GIT_URL/gitlab.com/github.com}"
 else
-	echo "$GIT_URL" # print error
+	echo "$GIT_URL" >&2 # print error
 fi
