autoformat

diff --git a/.local/scripts/generic/havecmd b/.local/scripts/generic/havecmd
--- a/.local/scripts/generic/havecmd
+++ b/.local/scripts/generic/havecmd
@@ -6,8 +6,8 @@
 
 BINARY="${1:?Must provide command to check}"
 if command -v "$BINARY" 2>&1 >/dev/null; then
-  exit 0
+	exit 0
 else
-  [ -n "$HAVECMD_REPORT" ] && printf "Could not find '%s' on your \$PATH\n" "$BINARY"
-  exit 1
+	[ -n "$HAVECMD_REPORT" ] && printf "Could not find '%s' on your \$PATH\n" "$BINARY"
+	exit 1
 fi
