autoformat shell code

diff --git a/.local/scripts/bin/gitopen b/.local/scripts/bin/gitopen
--- a/.local/scripts/bin/gitopen
+++ b/.local/scripts/bin/gitopen
@@ -1,20 +1,19 @@
 #!/usr/bin/env sh
 
-if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-  if ! remote_url="$(git ls-remote --get-url)"; then
-    printf "%s" "$remote_url"
-    exit 1
-  fi
-  if https_url="$(echo "$remote_url" | /usr/bin/python3 -c "from giturlparse import parse; print(parse(input()).urls['https'])" 2>/dev/null)"; then
-    echo "$https_url"
-    openurl "$https_url"
-    exit 0
-  else
-    printf "Could not parse %s into a HTTP URL properly.\n" "$remote_url"
-    exit 1
-  fi
+if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+	if ! remote_url="$(git ls-remote --get-url)"; then
+		printf "%s" "$remote_url"
+		exit 1
+	fi
+	if https_url="$(echo "$remote_url" | /usr/bin/python3 -c "from giturlparse import parse; print(parse(input()).urls['https'])" 2>/dev/null)"; then
+		echo "$https_url"
+		openurl "$https_url"
+		exit 0
+	else
+		printf "Could not parse %s into a HTTP URL properly.\n" "$remote_url"
+		exit 1
+	fi
 else
-  echo "Not currently in a git repo"
-  exit 1
+	echo "Not currently in a git repo"
+	exit 1
 fi
-
diff --git a/.local/scripts/system/editor b/.local/scripts/system/editor
--- a/.local/scripts/system/editor
+++ b/.local/scripts/system/editor
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-set -e  # exit on non zero return code
+set -e # exit on non zero return code
 set -u # undefined variables are errors
-
 
 usage="Usage: $(basename "$0") [OPTION] FILE...
 Opens an editor. If no options are provided,
@@ -31,41 +30,41 @@ ACTION=EMACS
 BG=
 
 while getopts "hncb" OPT; do
-   case "$OPT" in
-      h)
-         printf "%s" "$usage"
-         exit 0
-         ;;
-      n)
-         ACTION=NVIM
-         ;;
-      c)
-         ACTION=EMACS_CLIENT
-         ;;
-      b)
-         BG=true
-         ;;
-      ?)
-         printf "%s" "$usage"
-         exit 1
-         ;;
-   esac
+	case "$OPT" in
+	h)
+		printf "%s" "$usage"
+		exit 0
+		;;
+	n)
+		ACTION=NVIM
+		;;
+	c)
+		ACTION=EMACS_CLIENT
+		;;
+	b)
+		BG=true
+		;;
+	?)
+		printf "%s" "$usage"
+		exit 1
+		;;
+	esac
 done
 shift "$((OPTIND - 1))"
 
 # perform action
 case "$ACTION" in
-   NVIM)
-      nvim "$@"
-      ;;
-   EMACS)
-      emacs "$@" &
-      ;;
-   EMACS_CLIENT)
-      if [ "$BG" = true ]; then
-        emacsclient -c "$@" &
-      else
-        emacsclient -c "$@"
-      fi
-      ;;
+NVIM)
+	nvim "$@"
+	;;
+EMACS)
+	emacs "$@" &
+	;;
+EMACS_CLIENT)
+	if [ "$BG" = true ]; then
+		emacsclient -c "$@" &
+	else
+		emacsclient -c "$@"
+	fi
+	;;
 esac
