give: bash improvements

diff --git a/.local/scripts/bin/give b/.local/scripts/bin/give
--- a/.local/scripts/bin/give
+++ b/.local/scripts/bin/give
@@ -3,17 +3,19 @@
 # https://gitlab.com/seanbreckenridge/subpath-serve.git
 # and copies a link to that file to the clipboard
 
-BASE_URL="https://sean.fish/d/"
-SCRIPT_INDEX="$(curl -s "$BASE_URL")"
-SCRIPT_CHOICE="$(echo "$SCRIPT_INDEX" | fzf)" || exit 1
+ BASE_URL="https://sean.fish/d/"
+declare SCRIPT_INDEX="$(curl -s "$BASE_URL")"
+readonly SCRIPT_INDEX  # convert to constant
+declare SCRIPT_CHOICE  # define separately to not squash exit code
+SCRIPT_CHOICE="$(fzf <<<"$SCRIPT_INDEX")" || exit 1
 
 # if the URL can be reduced to just the base path, do that
-BASE_FILEPATHS="$(echo "$SCRIPT_INDEX" | rev | cut -d"/" -f1 | rev)"
-SCRIPT_BASE_CHOICE="$(echo "$SCRIPT_CHOICE" | rev | cut -d"/" -f1 | rev)"
-if [ "$(echo "$BASE_FILEPATHS" | grep -c "$SCRIPT_BASE_CHOICE")" = "1" ]; then
-	SCRIPT_CHOICE="$SCRIPT_BASE_CHOICE"
-fi
+declare BASE_FILEPATHS="$(echo -e "$SCRIPT_INDEX" | rev | cut -d"/" -f1 | rev)"
+readonly SCRIPT_BASE_CHOICE="$(echo -e "$SCRIPT_CHOICE" | rev | cut -d"/" -f1 | rev)"
+(( "$(grep -c "$SCRIPT_BASE_CHOICE"<<<"$BASE_FILEPATHS")" == 1 )) \
+&& SCRIPT_CHOICE="${SCRIPT_BASE_CHOICE}"
 
-GIVE_URL="${BASE_URL}${SCRIPT_CHOICE}?dark"
-echo "$GIVE_URL"
-echo -n "$GIVE_URL" | clipcopy
+# create the URL and copy it to my clipboard
+readonly GIVE_URL="${BASE_URL}${SCRIPT_CHOICE}?dark"
+echo -e "$GIVE_URL"
+echo -en "${GIVE_URL#$'\n'}" | clipcopy
