bootstrap: exit on calories error

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -304,7 +304,7 @@ if [[ -n "${GOBIN}" ]]; then
 	CALORIES_CONF_FILE="${GOBIN}/.caloriesconf"
 	[[ -e "${GOBIN}" ]] || mkdir -vp "${GOBIN}"
 	CALORIES_DB="${HOME}/data/calories.db"
-	[[ -e "${CALORIES_DB}" ]] || echo "Couldn't setup calories, database file doesn't exist"
+	[[ -e "${CALORIES_DB}" ]] || abort "Couldn't setup calories, database file doesn't exist"
 	printf '%s' "${CALORIES_DB}" >"${CALORIES_CONF_FILE}"
 	chmod +x "${CALORIES_CONF_FILE}"
 fi
