add comments to shortcuts

diff --git a/.local/share/shortcuts/image-dimensions b/.local/share/shortcuts/image-dimensions
--- a/.local/share/shortcuts/image-dimensions
+++ b/.local/share/shortcuts/image-dimensions
@@ -1,5 +1,6 @@
 #!/bin/sh
+# print the image dimensions for one or more images
 for f in "$@"; do
-	img_size="$(exiftool "$f" | grep "Image Size" | cut -d":" -f2)"
-	printf "%s:%s\n" "$f" "$img_size"
+	img_size="$(exiftool "$f" | grep "Image Size")"
+  [ -z "$img_size" ] && printf "Could not get 'Image Size' for %s" "$f" 1>&2 || printf "%s %s\n" "${img_size#*: }" "$f"
 done
