shellcheck improvements
shellcheck $(egrep -Hrin '#!/bin/sh|#!/usr/bin/env sh#!/bin/bash|#!/usr/bin/env bash' $(list-config) | grep -v zsh_history | grep -v 'shortcuts.toml' | cut -d':' -f1 | grep -v 'Binary')

diff --git a/.local/scripts/linux/macho b/.local/scripts/linux/macho
--- a/.local/scripts/linux/macho
+++ b/.local/scripts/linux/macho
@@ -1,37 +1,44 @@
-#!/bin/sh
+#!/bin/bash
+# Converted into bash from:
 # https://hiphish.github.io/blog/2020/05/31/macho-man-command-on-steroids/
 
-export FZF_DEFAULT_OPTS='
+declare -rx FZF_DEFAULT_OPTS='
 --height=30%
 --layout=reverse
 --prompt="Manual: "
---preview="echo {1} | sed -E \"s/^\((.+)\)/\1/\" | xargs -I{S} man -Pcat {S} {2} 2>/dev/null"'
+--preview="man -Pcat {S} {1} 2>/dev/null"'
 
 while getopts ":s:" opt; do
 	case $opt in
 	s)
-		SECTION=$OPTARG
+		SECTION="$OPTARG"
 		shift
 		shift
 		;;
 	\?)
-		echo "Invalid option: -$OPTARG" >&2
+		echo "Invalid option: -${OPTARG}" >&2
 		exit 1
 		;;
 	:)
-		echo "Option -$OPTARG requires an argument" >&2
+		echo "Option -${OPTARG} requires an argument" >&2
 		exit 1
 		;;
 	esac
 done
 
-manual=$(apropos -s ${SECTION:-''} ${@:-.} |
-	grep -v -E '^.+ \(0\)' |
-	awk '{print $2 "    " $1}' |
-	sort |
-	fzf |
-	sed -E 's/^\((.+)\)/\1/')
+declare -a APROPROS_ARGS
+APROPROS_ARGS=()
+# if user wanted a particular section, use that
+[[ -n "$SECTION" ]] && APROPROS_ARGS+=(-s "$SECTION")
+# use what the user passed, else . (everything)
+APROPROS_ARGS+=("${@:-.}")
 
-[ -z "$manual" ] && exit 0
-man $manual
+declare manual
+manual="$(apropos "${APROPROS_ARGS[@]}" |
+	grep -v -E '^.+ \(0\)' |
+	awk '{print $1}' |
+	sort |
+	fzf)" || exit $?
+
+man "${manual[@]}"
 printf '\r'  # fix cursor location
