spelling fixes

diff --git a/.config/zsh/aliases/project_aliases b/.config/zsh/aliases/project_aliases
--- a/.config/zsh/aliases/project_aliases
+++ b/.config/zsh/aliases/project_aliases
@@ -49,7 +49,7 @@ donelistening() {
 		return 1
 	}
 	[[ -z "$query" ]] && {
-		echo "no query given, cant remove matching paths..." >&2
+		echo "no query given, can't remove matching paths..." >&2
 		return 1
 	}
 	grep -vi "$query" <"$playlistfile" | sponge "$playlistfile"
diff --git a/.local/scripts/generic/dir-aliases-ranger b/.local/scripts/generic/dir-aliases-ranger
--- a/.local/scripts/generic/dir-aliases-ranger
+++ b/.local/scripts/generic/dir-aliases-ranger
@@ -16,7 +16,7 @@ readonly RangerDataDir="${XDG_DATA_HOME:-$HOME/.local/share}/ranger"
 }
 
 [[ ! -d "${RangerDataDir}" ]] && {
-	echo -e "Couldnt find ranger data directory at ${RangerDataDir}" >&2
+	echo -e "Couldn't find ranger data directory at ${RangerDataDir}" >&2
 	exit 1
 }
 
