editor: exit on unknown flags

diff --git a/.scripts/system/editor b/.scripts/system/editor
--- a/.scripts/system/editor
+++ b/.scripts/system/editor
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+set -e  # exit on non zero return code
+set -u # undefined variables are errors
+
+
 usage="Usage: $(basename "$0") [OPTION] FILE...
 Opens an editor. If no options are provided,
 opens the file(s) with emacs as a background process
@@ -41,10 +45,10 @@ while getopts "hncb" OPT; do
       b)
          BG=true
          ;;
-      -*)
-        printf "Invalid flag: %s\n" "$OPT" 1>&2
-        exit 1
-        ;;
+      ?)
+         printf "%s" "$usage"
+         exit 1
+         ;;
    esac
 done
 shift "$((OPTIND - 1))"
