use a .yadm/packages.txt to handle installing packages from bootstrap
fix funciton loading

diff --git a/.yadm/bootstrap b/.yadm/bootstrap
--- a/.yadm/bootstrap
+++ b/.yadm/bootstrap
@@ -1,22 +1,20 @@
 #!/bin/bash
+# yadm bootstrap script
+# Uses yay to install from AUR
 
-# Make sure required binaries/libraries are installed
-required_commands=("git" "rofi" "light" "wget" "pactl" "python3" "yadm")
-required_pacman_libraries=("xorg-server" "pulseaudio")
+if [ ! $(which yay) ]; then
+  echo -e "Could not find yay. Install that and re-run bootstrap\nExiting..."
+  exit 1
+fi
 
-echo 'Checking if requred commands are installed...'
-for cmd_name in "${required_commands[@]}"; do
-  if [[ ! $(which "${cmd_name}") ]]; then
-    echo -e "Required command ${cmd_name} is not installed\nExiting..."
-    exit 1
-  fi
-done
-
-echo 'Checking if required libraries are installed...'
-for library_name in "${required_libraries[@]}"; do
-  if pacman -Qs "$library_name" > /dev/null; then
-    echo -e "Required library ${library_name} is not installed\nExiting..."
-    exit 1
+echo "Checking ~/.yadm/packages.txt for any packages to install"
+for lib in $(cat ~/.yadm/packages.txt); do
+  if [[ ! $(yay -Qs "${lib}") ]]; then  # if package isn't installed
+    read -p "Do you want to install '${lib}'? [Y/n] " -n 1 -r
+    echo # newline
+    if [[ ! $REPLY =~ ^[Nn]$ ]]; then  # REPLY is automatically used as read variable
+      yay "${lib}"
+    fi
   fi
 done
 
